# .streamlit/secrets.toml

[connections.snowflake]
account = "OXWWRJA-RG90574"
user = "amushtaq1"
password = "Mnbf41526**"
role = "SYSADMIN" 
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true